# Generated by Django 5.2.17 on 2026-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicinecategory_medicine_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='pharmacies', to='myapp.medicine'),
        ),
    ]
