# Generated by Django 5.2.17 on 2026-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_medicine_image_pharmacyorder_pharmacyorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('DEMO', 'Демо-оплата, без списания')], default='DEMO', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='payment_status',
            field=models.CharField(choices=[('DEMO_PAID', 'Оплачено в демо-режиме')], default='DEMO_PAID', max_length=20),
        ),
    ]
