# Generated by Django 5.2.17 on 2026-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userwallet_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
