# Generated by Django 5.2.17 on 2026-10-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_doctorprofile_consultation_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='myapp.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_conversations', to='myapp.patientprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.doctorconversation')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_recommendations', to='myapp.medicine')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_recommendations', to='myapp.pharmacy')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorconversation',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='one_conversation_per_patient_doctor'),
        ),
        migrations.AddConstraint(
            model_name='doctormessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('medicine__isnull', True), ('pharmacy__isnull', True)), models.Q(('medicine__isnull', False), ('pharmacy__isnull', False)), _connector='OR'), name='doctor_message_medicine_pharmacy_pair'),
        ),
    ]
