# Generated by Django 5.2.17 on 2026-10-01 14:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('myapp', 'PharmacyOrder').objects.filter(
                payment_method='DEMO',
            ).update(payment_method='LEGACY', payment_status='UNPAID'),
            lambda apps, schema_editor: apps.get_model('myapp', 'PharmacyOrder').objects.filter(
                payment_method='LEGACY',
            ).update(payment_method='DEMO', payment_status='DEMO_PAID'),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('BALANCE', 'Баланс Careline'), ('LEGACY', 'Старый заказ — требуется оплата')], default='BALANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Оплачено с баланса'), ('UNPAID', 'Не оплачен')], default='PAID', max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOP_UP', 'Пополнение баланса'), ('PURCHASE', 'Покупка в аптеке')], max_length=12)),
                ('direction', models.CharField(choices=[('CREDIT', 'Зачисление'), ('DEBIT', 'Списание')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='myapp.pharmacyorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
