# Generated by Django 5.2.17 on 2026-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Картой'), ('BALANCE', 'Баланс Careline (ранее)'), ('LEGACY', 'Старый заказ — требуется оплата')], default='CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Оплачено'), ('UNPAID', 'Не оплачен')], default='PAID', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
