from django.urls import path

from .views import (
    CartAddView,
    CartItemRemoveView,
    CartItemUpdateView,
    appointment_detail,
    DoctorRegisterView,
    conversation_detail,
    doctor_detail,
    doctor_favorite,
    doctor_portal,
    DoctorReviewView,
    global_search,
    HomeView,
    MedicineOrderView,
    PatientRegisterView,
    PharmacyCheckoutView,
    robots_txt,
    ShoppingCartView,
    sitemap_xml,
    SymptomRouteView,
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    doctor_directory,
    message_inbox,
    pharmacy_detail,
    pharmacy_directory,
    profile,
    start_doctor_conversation,
)


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap_xml, name='sitemap_xml'),
    path('api/search/', global_search, name='global_search'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('register/patient/', PatientRegisterView.as_view(), {'role': 'patient'}, name='register_patient'),
    path('register/doctor/', DoctorRegisterView.as_view(), {'role': 'doctor'}, name='register_doctor'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('assistant/', SymptomRouteView.as_view(), name='assistant'),
    path('doctors/', doctor_directory, name='doctor_directory'),
    path('doctors/<int:doctor_id>/', doctor_detail, name='doctor_detail'),
    path('doctors/<int:doctor_id>/favorite/', doctor_favorite, name='doctor_favorite'),
    path('doctors/<int:doctor_id>/chat/', start_doctor_conversation, name='start_doctor_conversation'),
    path('appointments/<int:request_id>/', appointment_detail, name='appointment_detail'),
    path('doctor/portal/', doctor_portal, name='doctor_portal'),
    path('messages/', message_inbox, name='message_inbox'),
    path('messages/<int:conversation_id>/', conversation_detail, name='conversation_detail'),
    path('pharmacies/', pharmacy_directory, name='pharmacy_directory'),
    path('pharmacies/<int:pharmacy_id>/', pharmacy_detail, name='pharmacy_detail'),
    path('cart/', ShoppingCartView.as_view(), name='cart'),
    path('cart/add/', CartAddView.as_view(), name='cart_add'),
    path('cart/items/<int:item_id>/update/', CartItemUpdateView.as_view(), name='cart_item_update'),
    path('cart/items/<int:item_id>/remove/', CartItemRemoveView.as_view(), name='cart_item_remove'),
    path('cart/checkout/<int:pharmacy_id>/', PharmacyCheckoutView.as_view(), name='cart_checkout'),
    path('prescriptions/<int:prescription_id>/order/', MedicineOrderView.as_view(), name='medicine_order'),
    path('doctors/<int:doctor_id>/review/', DoctorReviewView.as_view(), name='doctor_review'),
]